index/urls.py
"""myprofile URL Configuration"""

from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='index-home'),
    path('profile/', views.profile, name='index-profile'),
    path('projects/', views.projects, name='index-projects'),
    path('friends/', views.friends, name='index-friends'),
]

myprofile/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
]

index/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

# Create your models here.
class Year(models.Model):
    year = models.IntegerField(primary_key=True)

    def __str__(self):
        return '%s' % self.year

class Data(models.Model):
    name = models.CharField(max_length=30, primary_key=True)
    hobby = models.CharField(max_length=30)
    your_year = models.ForeignKey(Year, on_delete=models.CASCADE)
    fnb = models.CharField(max_length=30)

    def __str__(self):
        return '%s' % self.name

index/forms.py
from django.forms import ModelForm
from .models import Data

class DataForm(ModelForm):
    class Meta:
        model = Data
        fields = ["name", "hobby", "fnb", "your_year"]

index/views.py
from django.shortcuts import render
from .forms import Data

from .models import Data, Year
from .forms import DataForm

# Create your views here.
def home(request):
    return render(request, 'index/index.html')

def profile(request):
    return render(request, 'index/profile.html')

def projects(request):
    return render(request, 'index/projects.html')

def friends(request):
    friends = Data.objects.all()
    return render(request, 'index/friends.html', {"friends":friends})

def add_friend(request):
    if request.method == 'POST':
        form = DataForm(request.POST)
        if form.is_valid():
            form.save()
            friends = Data.objects.all()
            return render(request, 'index/friends.html', {"friends":friends})
    
    else:
        form = DataForm()
    
    return render(request, 'index/friends.html')

index/templates/index/friends.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Forty by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Mohammad Saddam Mashuri</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />
		<noscript><link rel="stylesheet" href="{% static 'css/noscript.css' %}" /></noscript>
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<a href="{% url 'index-home' %}" class="logo"><strong>MSM</strong> <span>| Friends</span></a>
						<nav>
							<a href="#menu">Menu</a>
						</nav>
					</header>

				<!-- Menu -->
					{% include 'index/layouts/navbar.html' %}

				<!-- Main -->
					<div id="main" class="alt">

						<!-- One -->
							<section id="one">
							
								<div class="inner">
									<header class="major">
										<h1>Friends</h1>
									</header>
									{% for friend in friends %}
										<h2>{{ friend.name }}</h2>
										<p>
											Hobby: {{ friend.hobby }}
											<br>Favourite FnB: {{ friend.fnb }}
											<br>Class Year: {{ friend.your_year }}
											<br>
										</p>
									{% endfor %}
							<!-- Form -->
									<form method="post" action="">
									{% csrf_token %}
										<div class="fields">
											<div class="field half">
												<label for="name">Name</label>
												<input type="text" name="name" id="name" required placeholder="Name" />
											</div>
											<div class="field half">
												<label for="fnb">Favorite Food and Drinks</label>
												<input type="text" name="fnb" id="fnb" required placeholder="Pizza and Cola" />
											</div>
											<div class="field">
												<label for="hobby">Hobby</label>
												<textarea name="hobby" id="hobby" required rows="3"></textarea>
											</div>
											<div class="field half">
												<select name="your_year" id="id_your_year">
													<option value="">- Year -</option>
													<option value="2">2019</option>
													<option value="3">2018</option>
													<option value="4">2017</option>
													<option value="5">2016</option>
												</select>
											</div>
										</div>
										<ul class="actions">
											<li><input type="submit" value="Submit" class="primary" /></li>
											<li><input type="reset" value="Clear" /></li>
										</ul>
									</form>
									
									<!-- <form action="" method="post">
									{% csrf_token %}
									
									{{ form }}
									
									<input type="submit" value="Submit">
									</form> -->
								</div>
							</section>

					</div>

				<!-- Contact -->
					<section id="contact">
						<div class="inner">
							<section>
								<form method="post" action="#">
									<div class="fields">
										<div class="field half">
											<label for="cname">Name</label>
											<input type="text" name="cname" id="cname" />
										</div>
										<div class="field half">
											<label for="email">Email</label>
											<input type="text" name="email" id="email" />
										</div>
										<div class="field">
											<label for="message">Message</label>
											<textarea name="message" id="message" rows="6"></textarea>
										</div>
									</div>
									<ul class="actions">
										<li><input type="submit" value="Send Message" class="primary" /></li>
										<li><input type="reset" value="Clear" /></li>
									</ul>
								</form>
							</section>
							<section class="split">
								<section>
									<div class="contact-method">
										<span class="icon solid alt fa-envelope"></span>
										<h3>Email</h3>
										<a href="#">saddamonpc@gmail.com</a>
									</div>
								</section>
								<section>
									<div class="contact-method">
										<span class="icon solid alt fa-phone"></span>
										<h3>Phone</h3>
										<span>+62 878 6694 3392</span>
									</div>
								</section>
								<section>
									<div class="contact-method">
										<span class="icon solid alt fa-home"></span>
										<h3>Address</h3>
										<span>Jl. Margonda Raya No.525A, Kota Depok<br />
										Depok 16424<br />
										Indonesia</span>
									</div>
								</section>
							</section>
						</div>
					</section>

				<!-- Footer -->
					<footer id="footer">
						<div class="inner">
							<ul class="icons">
								<li><a href="https://www.instagram.com/saddamonpc/" class="icon brands alt fa-instagram"><span class="label">Instagram</span></a></li>
								<li><a href="https://github.com/saddamonpc" class="icon brands alt fa-github"><span class="label">GitHub</span></a></li>
							</ul>
							{% include 'index/layouts/copyright.html' %}
						</div>
					</footer>

			</div>

		<!-- Scripts -->
			<script src="{% static 'js/jquery.min.js' %}"></script>
			<script src="{% static 'js/jquery.scrolly.min.js' %}"></script>
			<script src="{% static 'js/jquery.scrollex.min.js' %}"></script>
			<script src="{% static 'js/browser.min.js' %}"></script>
			<script src="{% static 'js/breakpoints.min.js' %}"></script>
			<script src="{% static 'js/util.js' %}"></script>
			<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

index/templates/index/index.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Forty by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Mohammad Saddam Mashuri</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />
		<noscript><link rel="stylesheet" href="{% static 'css/noscript.css' %}" /></noscript>
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header" class="alt">
						<a href="{% url 'index-home' %}" class="logo"><strong>MSM</strong> <span>| Home</span></a>
						<nav>
							<a href="#menu">Menu</a>
						</nav>
					</header>

				<!-- Menu -->
					{% include 'index/layouts/navbar.html' %}

				<!-- Banner -->
					<section id="banner" class="major">
				<div class="inner">
							<span class="image">
								<img src="{% static "images/mountain.jpg" %}" alt="" />
							</span>
							<header class="major">
								<h1>Mohammad Saddam Mashuri, I am.</h1>
							</header>
				  <div class="content">
								<p>My portfolio page.</p>
					<ul class="actions">
					  <li><a href="{% url 'index-profile' %}" class="button primary">Profile</a></li>
						<li><a href="{% url 'index-projects' %}" class="button primary">Projects</a></li>
					</ul>
					<ul class="actions">
					<li><a href="#contact" class="button next scrolly">Contact me</a></li>
					</ul>
							</div>
						</div>
					</section>
<!-- Two -->
							<section id="two">
								<div class="inner">
									<header class="major">
										<h2>About Me</h2>
								  </header>
									<span class="image center"><img src="{% static "images/me.PNG" %}" alt="" /></span>
									<p>My name is Mohammad Saddam Mashuri. People usually call me Saddam. I am an undergraduate student in Universitas Indonesia majoring in Computer Science. You can usually find me browsing the internet, looking for some source of entertainment. Also, I rarely went outside unless I need to. One of the courses I'm currently studying is 'Web Design & Programming'. This site is one of the assignments I've been working on.</p>
							  </div>
			  </section>

	</div>
				<!-- Main -->
					<div id="main">

						<!-- One -->
							<section id="one" class="tiles">
								<article>
									<header class="major">
										<h3>Universitas Indonesia</h3>
										<p>Fakultas Ilmu Komputer</p>
										<p>MAUNG 2019</p>
										<p>NPM: 1906426891</p>
									</header>
								</article>
								<article>
									<header class="major">
										<h3>Hobbies</h3>
										<p>Playing games</p>
										<p>Guitar</p>
									</header>
								</article>
								
							</section>

						

				<!-- Contact -->
					<section id="contact">
						<div class="inner">
<section class="split">
		  <section>
									<div class="contact-method">
										<span class="icon solid alt fa-envelope"></span>
										<h3>Email</h3>
										<a href="#">saddamonpc@gmail.com</a>
									</div>
		</section>
								<section>
									<div class="contact-method">
										<span class="icon solid alt fa-phone"></span>
										<h3>Phone</h3>
										<span>(+62) 8786 6943 392</span>
									</div>
								</section>
								<section>
									<div class="contact-method">
										<span class="icon solid alt fa-home"></span>
										<h3>Address</h3>
										<span>Jl. Margonda Raya No.525A, Kota Depok<br />
										Depok 16424<br />
										Indonesia</span>
									</div>
								</section>
						  </section>
					  </div>
					</section>

				<!-- Footer -->
					<footer id="footer">
						<div class="inner">
							<ul class="icons">
								<li><a href="https://www.instagram.com/saddamonpc/" class="icon brands alt fa-instagram"><span class="label">Instagram</span></a></li>
								<li><a href="https://github.com/saddamonpc" class="icon brands alt fa-github"><span class="label">GitHub</span></a></li>
							</ul>
							{% include 'index/layouts/copyright.html' %}
						</div>
					</footer>

			</div>

		<!-- Scripts -->
			<script src="{% static 'js/jquery.min.js' %}"></script>
			<script src="{% static 'js/jquery.scrolly.min.js' %}"></script>
			<script src="{% static 'js/jquery.scrollex.min.js' %}"></script>
			<script src="{% static 'js/browser.min.js' %}"></script>
			<script src="{% static 'js/breakpoints.min.js' %}"></script>
			<script src="{% static 'js/util.js' %}"></script>
			<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

index/templates/index/layouts/copyright.html
<ul class="copyright">
	<li>&copy; Forty</li><li>Design: <a href="https://html5up.net">HTML5 UP</a></li>
	<li>&copy; Mohammad Saddam Mashuri 2020</li></li>
</ul>

index/templates/index/layouts/navbar.html
					<nav id="menu">
						<ul class="links">
							<li><a href="{% url 'index-home' %}">Home</a></li>
							<li><a href="{% url 'index-profile' %}">Profile</a></li>
							<li><a href="{% url 'index-projects' %}">Projects</a></li>
							<li><a href="{% url 'index-friends' %}">Friends</a></li>
						</ul>
					</nav>

index/templates/index/profile.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Forty by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Mohammad Saddam Mashuri</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />
		<noscript><link rel="stylesheet" href="{% static 'css/noscript.css' %}" /></noscript>
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<a href="{% url 'index-home' %}" class="logo"><strong>MSM</strong> <span>| Profile</span></a>
						<nav>
							<a href="#menu">Menu</a>
						</nav>
					</header>

				<!-- Menu -->
					{% include 'index/layouts/navbar.html' %}

				<!-- Main -->
					<div id="main" class="alt">

						<!-- One -->
							<section id="one">
							
								<div class="inner">
									<header class="major">
										<h1>Profile</h1>
									</header>
									<span class="image main"><img src="{% static "images/itisdone.jpg" %}" alt="" /></span>
									<p>Hi there, I am Saddam. I spend my days programming and producing music. I aspire to work in prominent companies, 
									such as Google, Intel, and etc. I've spent 3 years in Singapore while I was attending my 2nd year of middle school and 
									1st year of high school. I moved back to Indonesia in 2017 and got accepted in Universitas Indonesia majoring in Computer
									Science after graduating high school. I am staying here before going overseas again to continue my last 4 semesters in 2021 (hopefully).</p>
									<p>I'm constantly learning web design and other computer science related topics, currently playing around with
									Java and Javascript. Although I'm still amateur at these skills, I have great motivation to master it.</p>
									<p>I've dabbled in some organizations and participated in some competitions, such as:</p>
									<ul>
										<li>OSIS Documentary Division, 2016</li>
										<li>Participant of the Indonesian School of Singapore Physics Olympiad for Senior High School Level in Johor Bahru</li>
										<li>Finalist in a National Scale of Business and IT Olympiad (BIONIX 2018)</li>
									</ul>
									<p>For a more formal and complete overview of my life, please click the button below.</p>
									<a href="#" class="button primary icon solid fa-download">Download CV</a>
								</div>
							</section>

					</div>

				<!-- Contact -->
					<section id="contact">
						<div class="inner">
							<section>
								<form method="post" action="#">
									<div class="fields">
										<div class="field half">
											<label for="name">Name</label>
											<input type="text" name="name" id="name" />
										</div>
										<div class="field half">
											<label for="email">Email</label>
											<input type="text" name="email" id="email" />
										</div>
										<div class="field">
											<label for="message">Message</label>
											<textarea name="message" id="message" rows="6"></textarea>
										</div>
									</div>
									<ul class="actions">
										<li><input type="submit" value="Send Message" class="primary" /></li>
										<li><input type="reset" value="Clear" /></li>
									</ul>
								</form>
							</section>
							<section class="split">
								<section>
									<div class="contact-method">
										<span class="icon solid alt fa-envelope"></span>
										<h3>Email</h3>
										<a href="#">saddamonpc@gmail.com</a>
									</div>
								</section>
								<section>
									<div class="contact-method">
										<span class="icon solid alt fa-phone"></span>
										<h3>Phone</h3>
										<span>+62 878 6694 3392</span>
									</div>
								</section>
								<section>
									<div class="contact-method">
										<span class="icon solid alt fa-home"></span>
										<h3>Address</h3>
										<span>Jl. Margonda Raya No.525A, Kota Depok<br />
										Depok 16424<br />
										Indonesia</span>
									</div>
								</section>
							</section>
						</div>
					</section>

				<!-- Footer -->
					<footer id="footer">
						<div class="inner">
							<ul class="icons">
								<li><a href="https://www.instagram.com/saddamonpc/" class="icon brands alt fa-instagram"><span class="label">Instagram</span></a></li>
								<li><a href="https://github.com/saddamonpc" class="icon brands alt fa-github"><span class="label">GitHub</span></a></li>
							</ul>
							{% include 'index/layouts/copyright.html' %}
						</div>
					</footer>

			</div>

		<!-- Scripts -->
			<script src="{% static 'js/jquery.min.js' %}"></script>
			<script src="{% static 'js/jquery.scrolly.min.js' %}"></script>
			<script src="{% static 'js/jquery.scrollex.min.js' %}"></script>
			<script src="{% static 'js/browser.min.js' %}"></script>
			<script src="{% static 'js/breakpoints.min.js' %}"></script>
			<script src="{% static 'js/util.js' %}"></script>
			<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

index/templates/index/projects.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Forty by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Mohammad Saddam Mashuri</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />
		<noscript><link rel="stylesheet" href="{% static 'css/noscript.css' %}" /></noscript>
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
				<!-- Note: The "styleN" class below should match that of the banner element. -->
					<header id="header" class="alt style2">
						<a href="{% url 'index-home' %}" class="logo"><strong>MSM</strong> <span>| Projects</span></a>
						<nav>
							<a href="#menu">Menu</a>
						</nav>
					</header>

				<!-- Menu -->
					{% include 'index/layouts/navbar.html' %}

				<!-- Banner -->
				<!-- Note: The "styleN" class below should match that of the header element. -->
					<section id="banner" class="style1">
						<div class="inner">
							<span class="image">
								<img src="{% static "images/sadari.jpg" %}" alt="" />
							</span>
							<header class="major">
								<h1>Projects</h1>
							</header>
							<div class="content">
								<p>These are all projects I've done in the computer science field.</p>
							</div>
						</div>
					</section>

				<!-- Main -->
					<div id="main">

						<!-- Two -->
							<section id="two" class="spotlights">
								<section>
									<a href="{% url 'index-home' %}" class="image">
										<img src="{% static "images/homepage.PNG" %}" alt="" data-position="center center" />
									</a>
									<div class="content">
										<div class="inner">
											<header class="major">
												<h2>Project 1</h2>
											</header>
											<p>My website! You are here right now!</p>
											<ul class="actions">
												<li><a href="{% url 'index-home' %}" class="button">Learn more</a></li>
											</ul>
										</div>
									</div>
								</section>
								<section>
									<a href="{% url 'index-home' %}" class="image">
										<img src="{% static "images/pic09.jpg" %}" alt="" data-position="top center" />
									</a>
									<div class="content">
										<div class="inner">
											<header class="major">
												<h2>Project 2</h2>
											</header>
											<p>Coming soon!</p>
											<ul class="actions">
												<li><a href="{% url 'index-home' %}" class="button">Learn more</a></li>
											</ul>
										</div>
									</div>
								</section>
								<section>
									<a href="{% url 'index-home' %}" class="image">
										<img src="{% static "images/pic10.jpg" %}" alt="" data-position="25% 25%" />
									</a>
									<div class="content">
										<div class="inner">
											<header class="major">
												<h2>Project 3</h2>
											</header>
											<p>Coming soon!</p>
											<ul class="actions">
												<li><a href="{% url 'index-home' %}" class="button">Learn more</a></li>
											</ul>
										</div>
									</div>
								</section>
							</section>

					</div>

				<!-- Contact -->
					<section id="contact">
						<div class="inner">
							<section>
								<form method="post" action="#">
									<div class="fields">
										<div class="field half">
											<label for="name">Name</label>
											<input type="text" name="name" id="name" />
										</div>
										<div class="field half">
											<label for="email">Email</label>
											<input type="text" name="email" id="email" />
										</div>
										<div class="field">
											<label for="message">Message</label>
											<textarea name="message" id="message" rows="6"></textarea>
										</div>
									</div>
									<ul class="actions">
										<li><input type="submit" value="Send Message" class="primary" /></li>
										<li><input type="reset" value="Clear" /></li>
									</ul>
								</form>
							</section>
							<section class="split">
								<section>
									<div class="contact-method">
										<span class="icon solid alt fa-envelope"></span>
										<h3>Email</h3>
										<a href="#">saddamonpc@gmail.com</a>
									</div>
								</section>
								<section>
									<div class="contact-method">
										<span class="icon solid alt fa-phone"></span>
										<h3>Phone</h3>
										<span>+62 878 6694 3392</span>
									</div>
								</section>
								<section>
									<div class="contact-method">
										<span class="icon solid alt fa-home"></span>
										<h3>Address</h3>
										<span>Jl. Margonda Raya No.525A, Kota Depok<br />
										Depok 16424<br />
										Indonesia</span>
									</div>
								</section>
							</section>
						</div>
					</section>

				<!-- Footer -->
					<footer id="footer">
						<div class="inner">
							<ul class="icons">
								<li><a href="https://www.instagram.com/saddamonpc/" class="icon brands alt fa-instagram"><span class="label">Instagram</span></a></li>
								<li><a href="https://github.com/saddamonpc" class="icon brands alt fa-github"><span class="label">GitHub</span></a></li>
							</ul>
							{% include 'index/layouts/copyright.html' %}
							</ul>
						</div>
					</footer>

			</div>

		<!-- Scripts -->
			<script src="{% static 'js/jquery.min.js' %}"></script>
			<script src="{% static 'js/jquery.scrolly.min.js' %}"></script>
			<script src="{% static 'js/jquery.scrollex.min.js' %}"></script>
			<script src="{% static 'js/browser.min.js' %}"></script>
			<script src="{% static 'js/breakpoints.min.js' %}"></script>
			<script src="{% static 'js/util.js' %}"></script>
			<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>